INFO 2025-10-18 11:44:01,216 autoreload 18128 1652 Watching for file changes with StatReloader
INFO 2025-10-18 11:45:04,280 autoreload 18128 1652 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\pristineprimer\settings.py changed, reloading.
INFO 2025-10-18 11:45:05,970 autoreload 24264 22800 Watching for file changes with StatReloader
ERROR 2025-10-18 11:46:05,048 log 24264 18152 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 11:46:05,055 basehttp 24264 18152 "GET / HTTP/1.1" 500 91662
INFO 2025-10-18 11:46:18,083 basehttp 24264 20432 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-10-18 11:46:18,131 basehttp 24264 20432 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4205
INFO 2025-10-18 11:46:18,348 basehttp 24264 20432 "GET /static/admin/css/login.css HTTP/1.1" 200 951
WARNING 2025-10-18 11:46:18,970 log 24264 20432 Not Found: /api/orders/
WARNING 2025-10-18 11:46:18,972 basehttp 24264 20432 "GET /api/orders/ HTTP/1.1" 404 11022
INFO 2025-10-18 11:52:04,908 basehttp 24264 2696 "GET /admin/payments/mpesaconfiguration/add/ HTTP/1.1" 302 0
INFO 2025-10-18 11:52:04,967 basehttp 24264 2696 "GET /admin/login/?next=/admin/payments/mpesaconfiguration/add/ HTTP/1.1" 200 4269
INFO 2025-10-18 12:48:36,285 basehttp 24264 23192 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 12:48:36,600 basehttp 24264 23916 "OPTIONS /api/auth/me/ HTTP/1.1" 200 0
INFO 2025-10-18 12:48:36,619 basehttp 24264 23192 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 12:48:40,274 basehttp 24264 23192 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 12:48:40,282 basehttp 24264 23192 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 12:48:40,516 basehttp 24264 23916 "OPTIONS /api/properties/?featured=true&limit=6 HTTP/1.1" 200 0
INFO 2025-10-18 12:48:40,621 basehttp 24264 2100 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 12:48:41,272 basehttp 24264 23192 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 788
INFO 2025-10-18 12:48:41,397 basehttp 24264 23192 "GET /media/property_images/ChatGPT_Image_Sep_13_2025_02_47_02_PM_obfB0IH.png HTTP/1.1" 200 2462478
INFO 2025-10-18 12:48:41,460 basehttp 24264 23192 "GET /media/property_images/ChatGPT_Image_Sep_13_2025_02_47_02_PM.png HTTP/1.1" 200 2462478
INFO 2025-10-18 13:04:12,387 basehttp 24264 20328 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:04:12,424 basehttp 24264 20328 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 13:18:08,054 basehttp 24264 19668 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:18:08,061 basehttp 24264 19668 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:18:08,290 basehttp 24264 19668 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 788
INFO 2025-10-18 13:18:08,295 basehttp 24264 19668 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 13:25:31,384 basehttp 24264 21432 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:25:31,613 basehttp 24264 21432 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 788
INFO 2025-10-18 13:27:22,077 basehttp 24264 21316 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:27:22,250 basehttp 24264 21316 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 788
INFO 2025-10-18 13:27:34,245 basehttp 24264 20012 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:27:34,572 basehttp 24264 14628 "OPTIONS /api/properties/2/ HTTP/1.1" 200 0
INFO 2025-10-18 13:27:34,721 basehttp 24264 20012 "GET /api/properties/2/ HTTP/1.1" 200 837
INFO 2025-10-18 13:27:45,897 basehttp 24264 5184 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:27:46,071 basehttp 24264 5184 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 788
INFO 2025-10-18 13:27:53,459 basehttp 24264 10116 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:27:53,798 basehttp 24264 24248 "OPTIONS /api/properties/1/ HTTP/1.1" 200 0
INFO 2025-10-18 13:27:53,947 basehttp 24264 10116 "GET /api/properties/1/ HTTP/1.1" 200 1003
INFO 2025-10-18 13:27:53,998 basehttp 24264 10116 "GET /media/property_images/delivery-man-on-motorcycle-with-package-vector.jpg HTTP/1.1" 200 72060
INFO 2025-10-18 13:37:21,426 basehttp 24264 18092 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 13:37:21,610 basehttp 24264 18092 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 788
INFO 2025-10-18 14:35:23,755 autoreload 24264 22800 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\models.py changed, reloading.
INFO 2025-10-18 14:35:27,107 autoreload 25176 23704 Watching for file changes with StatReloader
INFO 2025-10-18 14:39:55,688 autoreload 25176 23704 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 14:39:57,183 autoreload 4952 3076 Watching for file changes with StatReloader
INFO 2025-10-18 14:40:04,671 autoreload 4952 3076 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 14:40:06,298 autoreload 8216 16460 Watching for file changes with StatReloader
INFO 2025-10-18 14:40:17,651 autoreload 8216 16460 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 14:40:18,763 autoreload 1500 21624 Watching for file changes with StatReloader
INFO 2025-10-18 14:40:32,780 autoreload 1500 21624 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 14:40:33,983 autoreload 3480 12760 Watching for file changes with StatReloader
INFO 2025-10-18 15:02:59,949 autoreload 3480 12760 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\admin.py changed, reloading.
INFO 2025-10-18 15:03:02,016 autoreload 16224 22200 Watching for file changes with StatReloader
INFO 2025-10-18 15:08:07,977 autoreload 16224 22200 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\views.py changed, reloading.
INFO 2025-10-18 15:08:09,773 autoreload 8860 16236 Watching for file changes with StatReloader
INFO 2025-10-18 15:11:06,325 autoreload 8860 16236 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 15:11:08,247 autoreload 15632 19620 Watching for file changes with StatReloader
INFO 2025-10-18 15:16:58,564 autoreload 15632 19620 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\filters.py changed, reloading.
INFO 2025-10-18 15:17:00,248 autoreload 19664 21996 Watching for file changes with StatReloader
INFO 2025-10-18 15:17:05,633 autoreload 19664 21996 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\filters.py changed, reloading.
INFO 2025-10-18 15:17:07,979 autoreload 21304 24944 Watching for file changes with StatReloader
INFO 2025-10-18 15:17:10,535 autoreload 21304 24944 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\filters.py changed, reloading.
INFO 2025-10-18 15:17:11,965 autoreload 19936 2160 Watching for file changes with StatReloader
INFO 2025-10-18 15:18:57,200 autoreload 19936 2160 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\pristineprimer\settings.py changed, reloading.
INFO 2025-10-18 15:18:58,685 autoreload 17276 13204 Watching for file changes with StatReloader
INFO 2025-10-18 15:22:16,842 autoreload 17276 13204 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:22:18,587 autoreload 24648 21448 Watching for file changes with StatReloader
INFO 2025-10-18 15:22:30,095 autoreload 24648 21448 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:22:31,580 autoreload 25008 4420 Watching for file changes with StatReloader
INFO 2025-10-18 15:26:13,445 autoreload 25008 4420 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\models.py changed, reloading.
INFO 2025-10-18 15:26:15,638 autoreload 8800 3312 Watching for file changes with StatReloader
INFO 2025-10-18 15:26:20,798 autoreload 8800 3312 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\models.py changed, reloading.
INFO 2025-10-18 15:26:22,064 autoreload 23952 2076 Watching for file changes with StatReloader
INFO 2025-10-18 15:27:42,470 autoreload 23952 2076 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\admin.py changed, reloading.
INFO 2025-10-18 15:27:43,570 autoreload 20280 21952 Watching for file changes with StatReloader
INFO 2025-10-18 15:30:17,819 autoreload 20280 21952 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:30:19,898 autoreload 11696 2056 Watching for file changes with StatReloader
INFO 2025-10-18 15:32:08,285 autoreload 11696 2056 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:32:10,615 autoreload 14700 10060 Watching for file changes with StatReloader
INFO 2025-10-18 15:36:01,815 autoreload 14700 10060 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:36:03,916 autoreload 17520 25060 Watching for file changes with StatReloader
INFO 2025-10-18 15:36:46,659 autoreload 17520 25060 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:36:48,132 autoreload 13280 9436 Watching for file changes with StatReloader
INFO 2025-10-18 15:37:22,448 basehttp 13280 13644 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-10-18 15:37:22,555 basehttp 13280 13644 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4205
INFO 2025-10-18 15:37:22,848 basehttp 13280 13964 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-10-18 15:37:22,853 basehttp 13280 24300 "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-10-18 15:37:22,854 basehttp 13280 13644 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-10-18 15:37:22,855 basehttp 13280 13964 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-10-18 15:37:22,868 basehttp 13280 13964 "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-10-18 15:37:22,871 basehttp 13280 13644 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
ERROR 2025-10-18 15:37:23,894 log 13280 13644 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 15:37:23,906 basehttp 13280 13644 "GET /favicon.ico HTTP/1.1" 500 92199
INFO 2025-10-18 15:37:34,554 basehttp 13280 19528 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-10-18 15:37:34,659 basehttp 13280 19528 "GET /admin/ HTTP/1.1" 200 20863
INFO 2025-10-18 15:37:34,719 basehttp 13280 19528 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-10-18 15:37:34,739 basehttp 13280 19528 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-10-18 15:37:34,739 basehttp 13280 23604 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
ERROR 2025-10-18 15:37:35,029 log 13280 23604 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 15:37:35,036 basehttp 13280 23604 "GET /favicon.ico HTTP/1.1" 500 92343
INFO 2025-10-18 15:37:49,901 basehttp 13280 2636 "GET /admin/properties/property/add/ HTTP/1.1" 200 101741
INFO 2025-10-18 15:37:49,954 basehttp 13280 22228 "GET /static/admin/css/autocomplete.css HTTP/1.1" 200 9185
INFO 2025-10-18 15:37:49,955 basehttp 13280 2636 "GET /static/admin/css/vendor/select2/select2.css HTTP/1.1" 200 17358
INFO 2025-10-18 15:37:49,969 basehttp 13280 2636 "GET /static/admin/js/autocomplete.js HTTP/1.1" 200 1060
INFO 2025-10-18 15:37:49,974 basehttp 13280 22228 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-10-18 15:37:49,978 basehttp 13280 2636 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-10-18 15:37:49,978 basehttp 13280 1228 "GET /static/admin/js/inlines.js HTTP/1.1" 200 15628
INFO 2025-10-18 15:37:49,983 basehttp 13280 23816 "GET /static/admin/js/vendor/select2/select2.full.js HTTP/1.1" 200 173566
INFO 2025-10-18 15:37:49,994 basehttp 13280 2636 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-10-18 15:37:49,984 basehttp 13280 21952 "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
INFO 2025-10-18 15:37:49,987 basehttp 13280 22228 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-10-18 15:37:49,983 basehttp 13280 17684 "GET /static/admin/js/vendor/select2/i18n/en.js HTTP/1.1" 200 844
INFO 2025-10-18 15:37:49,998 basehttp 13280 1228 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
INFO 2025-10-18 15:37:49,998 basehttp 13280 23816 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-10-18 15:37:50,010 basehttp 13280 2636 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11973
INFO 2025-10-18 15:37:50,016 basehttp 13280 22228 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-10-18 15:37:50,016 basehttp 13280 17684 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-10-18 15:37:50,034 basehttp 13280 17684 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-10-18 15:37:50,053 basehttp 13280 17684 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-10-18 15:37:50,059 basehttp 13280 17684 "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
INFO 2025-10-18 15:37:50,065 basehttp 13280 17684 "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2025-10-18 15:37:50,070 basehttp 13280 17684 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-10-18 15:37:50,114 basehttp 13280 21952 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-18 15:37:50,315 basehttp 13280 21952 "GET /static/admin/img/inline-delete.svg HTTP/1.1" 200 537
ERROR 2025-10-18 15:37:50,506 log 13280 21952 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 15:37:50,511 basehttp 13280 21952 "GET /favicon.ico HTTP/1.1" 500 92367
INFO 2025-10-18 15:39:55,413 autoreload 13280 9436 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\pristineprimer\settings.py changed, reloading.
INFO 2025-10-18 15:39:57,479 autoreload 15464 15688 Watching for file changes with StatReloader
INFO 2025-10-18 15:40:59,933 autoreload 15464 15688 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:41:01,471 autoreload 11544 21912 Watching for file changes with StatReloader
INFO 2025-10-18 15:41:11,868 autoreload 11544 21912 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:41:13,290 autoreload 588 7680 Watching for file changes with StatReloader
INFO 2025-10-18 15:42:02,736 autoreload 588 7680 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\pristineprimer\urls.py changed, reloading.
INFO 2025-10-18 15:42:04,470 autoreload 16596 1436 Watching for file changes with StatReloader
INFO 2025-10-18 15:42:17,641 autoreload 16596 1436 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\urls.py changed, reloading.
INFO 2025-10-18 15:42:19,373 autoreload 7112 6408 Watching for file changes with StatReloader
INFO 2025-10-18 15:42:23,217 autoreload 7112 6408 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\pristineprimer\urls.py changed, reloading.
INFO 2025-10-18 15:42:24,755 autoreload 15192 10584 Watching for file changes with StatReloader
INFO 2025-10-18 15:48:38,685 basehttp 15192 21440 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 15:48:39,001 basehttp 15192 16700 "OPTIONS /api/properties/1/ HTTP/1.1" 200 0
INFO 2025-10-18 15:48:39,246 basehttp 15192 21440 "GET /api/properties/1/ HTTP/1.1" 200 2055
INFO 2025-10-18 15:48:48,709 basehttp 15192 11988 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 15:48:49,029 basehttp 15192 23328 "OPTIONS /api/properties/? HTTP/1.1" 200 0
INFO 2025-10-18 15:48:49,205 basehttp 15192 11988 "GET /api/properties/? HTTP/1.1" 200 1944
INFO 2025-10-18 15:49:04,945 basehttp 15192 3264 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 15:49:05,175 basehttp 15192 3264 "GET /api/properties/1/ HTTP/1.1" 200 2055
INFO 2025-10-18 16:52:22,218 basehttp 15192 10712 "OPTIONS /api/auth/me/ HTTP/1.1" 200 0
INFO 2025-10-18 16:52:22,251 basehttp 15192 25544 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 16:52:22,604 basehttp 15192 14944 "GET /api/properties/1/ HTTP/1.1" 200 2055
INFO 2025-10-18 16:52:27,894 basehttp 15192 16236 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 16:52:28,203 basehttp 15192 21152 "OPTIONS /api/properties/?featured=true&limit=6 HTTP/1.1" 200 0
INFO 2025-10-18 16:52:28,364 basehttp 15192 16236 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1056
INFO 2025-10-18 16:52:38,789 basehttp 15192 18148 "GET /admin/properties/property/add/ HTTP/1.1" 200 101741
ERROR 2025-10-18 16:52:39,522 log 15192 18148 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 16:52:39,532 basehttp 15192 18148 "GET /favicon.ico HTTP/1.1" 500 92503
INFO 2025-10-18 16:59:22,087 basehttp 15192 14988 "GET /admin/ HTTP/1.1" 200 20863
ERROR 2025-10-18 16:59:22,328 log 15192 14988 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 16:59:22,334 basehttp 15192 14988 "GET /favicon.ico HTTP/1.1" 500 92479
INFO 2025-10-18 16:59:33,645 basehttp 15192 17288 "GET /admin/properties/property/add/ HTTP/1.1" 200 101741
INFO 2025-10-18 16:59:33,958 basehttp 15192 17288 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 16:59:34,203 log 15192 17288 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 16:59:34,209 basehttp 15192 17288 "GET /favicon.ico HTTP/1.1" 500 92503
INFO 2025-10-18 17:05:22,625 basehttp 15192 24844 "GET /admin/autocomplete/?app_label=properties&model_name=propertyamenity&field_name=amenity HTTP/1.1" 200 46
INFO 2025-10-18 17:05:26,115 basehttp 15192 24844 "GET /admin/autocomplete/?app_label=properties&model_name=propertyamenity&field_name=amenity HTTP/1.1" 200 46
INFO 2025-10-18 17:05:28,245 basehttp 15192 24844 "GET /admin/autocomplete/?app_label=properties&model_name=propertyamenity&field_name=amenity HTTP/1.1" 200 46
INFO 2025-10-18 17:05:30,949 basehttp 15192 24844 "GET /admin/autocomplete/?term=ho&app_label=properties&model_name=propertyamenity&field_name=amenity HTTP/1.1" 200 46
INFO 2025-10-18 17:05:31,802 basehttp 15192 24844 "GET /admin/autocomplete/?term=hos&app_label=properties&model_name=propertyamenity&field_name=amenity HTTP/1.1" 200 46
INFO 2025-10-18 17:05:32,179 basehttp 15192 24844 - Broken pipe from ('127.0.0.1', 55465)
INFO 2025-10-18 17:05:32,480 basehttp 15192 23580 - Broken pipe from ('127.0.0.1', 55479)
INFO 2025-10-18 17:05:32,805 basehttp 15192 20680 - Broken pipe from ('127.0.0.1', 55481)
INFO 2025-10-18 17:05:33,053 basehttp 15192 3532 - Broken pipe from ('127.0.0.1', 55484)
INFO 2025-10-18 17:05:33,346 basehttp 15192 18512 "GET /admin/autocomplete/?term=hospital&app_label=properties&model_name=propertyamenity&field_name=amenity HTTP/1.1" 200 46
INFO 2025-10-18 17:05:37,163 basehttp 15192 18512 "GET /admin/properties/amenity/add/?_to_field=id&_popup=1 HTTP/1.1" 200 7383
INFO 2025-10-18 17:05:37,283 basehttp 15192 18512 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:05:37,465 log 15192 18512 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:05:37,469 basehttp 15192 18512 "GET /favicon.ico HTTP/1.1" 500 92528
INFO 2025-10-18 17:06:01,772 basehttp 15192 22444 "POST /admin/properties/amenity/add/?_to_field=id&_popup=1 HTTP/1.1" 200 349
INFO 2025-10-18 17:06:01,936 basehttp 15192 22444 "GET /static/admin/js/popup_response.js HTTP/1.1" 200 532
INFO 2025-10-18 17:06:03,618 basehttp 15192 22444 "GET /admin/autocomplete/?app_label=properties&model_name=propertyamenity&field_name=amenity HTTP/1.1" 200 98
INFO 2025-10-18 17:09:52,094 basehttp 15192 21400 "POST /admin/properties/property/add/ HTTP/1.1" 200 105275
WARNING 2025-10-18 17:09:52,195 log 15192 25064 Not Found: /media/images (5).jpeg
WARNING 2025-10-18 17:09:52,201 basehttp 15192 25064 "GET /media/images%20(5).jpeg HTTP/1.1" 404 3289
WARNING 2025-10-18 17:09:52,219 log 15192 21728 Not Found: /media/download.jpeg
WARNING 2025-10-18 17:09:52,234 basehttp 15192 21728 "GET /media/download.jpeg HTTP/1.1" 404 3279
INFO 2025-10-18 17:09:52,288 basehttp 15192 21400 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:09:52,688 log 15192 21400 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:09:52,700 basehttp 15192 21400 "GET /favicon.ico HTTP/1.1" 500 92503
INFO 2025-10-18 17:10:40,826 basehttp 15192 25148 "POST /admin/properties/property/add/ HTTP/1.1" 200 105675
INFO 2025-10-18 17:10:40,951 basehttp 15192 25148 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:10:41,207 log 15192 25148 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:10:41,211 basehttp 15192 25148 "GET /favicon.ico HTTP/1.1" 500 92503
INFO 2025-10-18 17:13:17,790 basehttp 15192 9192 "POST /admin/properties/property/add/ HTTP/1.1" 302 0
INFO 2025-10-18 17:13:17,931 basehttp 15192 9192 "GET /admin/properties/property/ HTTP/1.1" 200 35470
INFO 2025-10-18 17:13:17,974 basehttp 15192 20360 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-10-18 17:13:17,974 basehttp 15192 9192 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-10-18 17:13:17,987 basehttp 15192 14696 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-10-18 17:13:17,987 basehttp 15192 9192 "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2025-10-18 17:13:18,002 basehttp 15192 9192 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-10-18 17:13:18,088 basehttp 15192 6896 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-18 17:13:18,128 basehttp 15192 9192 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-10-18 17:13:18,128 basehttp 15192 6896 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
ERROR 2025-10-18 17:13:18,391 log 15192 6896 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:13:18,499 basehttp 15192 6896 "GET /favicon.ico HTTP/1.1" 500 92499
INFO 2025-10-18 17:13:25,459 basehttp 15192 22812 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:13:25,462 basehttp 15192 22812 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:13:25,658 basehttp 15192 22812 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:13:25,662 basehttp 15192 22812 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 17:13:25,721 basehttp 15192 22812 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 200 11615
INFO 2025-10-18 17:13:47,057 basehttp 15192 4916 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:13:47,371 basehttp 15192 3040 "OPTIONS /api/properties/5/ HTTP/1.1" 200 0
INFO 2025-10-18 17:13:47,519 basehttp 15192 4916 "GET /api/properties/5/ HTTP/1.1" 200 4336
INFO 2025-10-18 17:13:47,538 basehttp 15192 20636 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:13:47,539 basehttp 15192 4916 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 200 11102
INFO 2025-10-18 17:14:07,521 basehttp 15192 8828 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:14:07,690 basehttp 15192 8828 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:14:17,322 basehttp 15192 17348 "GET /admin/properties/property/5/change/ HTTP/1.1" 200 116397
INFO 2025-10-18 17:14:17,374 basehttp 15192 9072 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 200 11615
INFO 2025-10-18 17:14:17,380 basehttp 15192 3696 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 200 11102
INFO 2025-10-18 17:14:17,449 basehttp 15192 17348 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:14:17,781 log 15192 17348 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:14:17,785 basehttp 15192 17348 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 17:15:22,060 basehttp 15192 11980 "POST /admin/properties/property/5/change/ HTTP/1.1" 200 116668
INFO 2025-10-18 17:15:22,101 basehttp 15192 244 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:15:22,103 basehttp 15192 23604 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:15:22,303 basehttp 15192 11980 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:15:22,508 log 15192 11980 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:15:22,512 basehttp 15192 11980 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 17:15:57,509 basehttp 15192 24304 "POST /admin/properties/property/5/change/ HTTP/1.1" 200 116858
INFO 2025-10-18 17:15:57,565 basehttp 15192 1816 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:15:57,566 basehttp 15192 23944 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:15:57,650 basehttp 15192 24304 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:15:57,868 log 15192 24304 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:15:57,872 basehttp 15192 24304 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 17:17:15,186 basehttp 15192 18128 "POST /admin/properties/property/5/change/ HTTP/1.1" 200 116732
INFO 2025-10-18 17:17:15,229 basehttp 15192 21416 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:17:15,231 basehttp 15192 19856 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:17:15,300 basehttp 15192 18128 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:17:15,506 log 15192 18128 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:17:15,511 basehttp 15192 18128 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 17:17:42,898 basehttp 15192 19636 "POST /admin/properties/property/5/change/ HTTP/1.1" 302 0
INFO 2025-10-18 17:17:43,015 basehttp 15192 19636 "GET /admin/properties/property/ HTTP/1.1" 200 35475
INFO 2025-10-18 17:17:43,279 basehttp 15192 19636 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:17:43,485 log 15192 19636 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:17:43,491 basehttp 15192 19636 "GET /favicon.ico HTTP/1.1" 500 92499
INFO 2025-10-18 17:17:52,513 basehttp 15192 1652 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:17:52,518 basehttp 15192 1652 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:17:52,830 basehttp 15192 14676 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 17:17:52,832 basehttp 15192 1652 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:17:52,915 basehttp 15192 1652 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:18:00,414 basehttp 15192 1652 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:18:00,414 basehttp 15192 14676 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:18:00,800 basehttp 15192 3276 "OPTIONS /api/auth/me/ HTTP/1.1" 200 0
INFO 2025-10-18 17:18:00,801 basehttp 15192 3712 "OPTIONS /api/properties/?featured=true&limit=6 HTTP/1.1" 200 0
INFO 2025-10-18 17:18:00,839 basehttp 15192 14676 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 17:18:00,992 basehttp 15192 1652 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:18:21,124 basehttp 15192 11680 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:18:21,270 basehttp 15192 11680 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 17:18:21,289 basehttp 15192 11680 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:18:36,903 basehttp 15192 9088 "GET /admin/properties/property/5/change/ HTTP/1.1" 200 116494
INFO 2025-10-18 17:18:36,946 basehttp 15192 11120 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:18:36,947 basehttp 15192 24704 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:18:37,020 basehttp 15192 9088 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:18:37,253 log 15192 9088 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:18:37,260 basehttp 15192 9088 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 17:18:41,151 basehttp 15192 9088 "GET /admin/properties/property/ HTTP/1.1" 200 35246
ERROR 2025-10-18 17:18:41,346 log 15192 9088 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:18:41,350 basehttp 15192 9088 "GET /favicon.ico HTTP/1.1" 500 92499
INFO 2025-10-18 17:18:43,900 basehttp 15192 22796 "GET /admin/properties/property/5/change/ HTTP/1.1" 200 116494
INFO 2025-10-18 17:18:44,014 basehttp 15192 22796 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:18:44,239 log 15192 22796 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:18:44,245 basehttp 15192 22796 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 17:19:03,326 basehttp 15192 16108 "GET /admin/properties/property/ HTTP/1.1" 200 35246
ERROR 2025-10-18 17:19:03,531 log 15192 16108 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:19:03,534 basehttp 15192 16108 "GET /favicon.ico HTTP/1.1" 500 92499
INFO 2025-10-18 17:19:17,190 basehttp 15192 19924 "GET /admin/properties/property/5/change/ HTTP/1.1" 200 116494
INFO 2025-10-18 17:19:17,240 basehttp 15192 24932 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:19:17,245 basehttp 15192 1940 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:19:17,317 basehttp 15192 19924 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 17:19:17,604 log 15192 19924 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:19:17,610 basehttp 15192 19924 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 17:20:49,843 basehttp 15192 19608 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:20:49,993 basehttp 15192 19608 "GET /api/properties/? HTTP/1.1" 200 2643
INFO 2025-10-18 17:20:58,882 basehttp 15192 19608 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:20:59,113 basehttp 15192 19608 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:21:33,981 basehttp 15192 22876 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:21:34,236 basehttp 15192 22876 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 17:21:34,261 basehttp 15192 22876 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:23:34,376 basehttp 15192 18052 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:23:34,762 basehttp 15192 18052 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:23:44,270 basehttp 15192 8560 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:23:44,470 basehttp 15192 8560 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 17:23:44,492 basehttp 15192 8560 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:23:48,596 basehttp 15192 20612 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:23:48,798 basehttp 15192 20612 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:23:48,870 basehttp 15192 20612 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:33:49,258 basehttp 15192 15120 "GET /admin/properties/property/5/change/ HTTP/1.1" 200 116494
ERROR 2025-10-18 17:33:49,877 log 15192 15120 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:33:49,880 basehttp 15192 15120 "GET /favicon.ico HTTP/1.1" 500 92508
ERROR 2025-10-18 17:33:52,910 log 15192 15120 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:33:52,917 basehttp 15192 15120 "GET / HTTP/1.1" 500 92570
ERROR 2025-10-18 17:33:53,226 log 15192 15120 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 17:33:53,232 basehttp 15192 15120 "GET /favicon.ico HTTP/1.1" 500 92473
INFO 2025-10-18 17:35:39,085 basehttp 15192 21808 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:35:39,102 basehttp 15192 21808 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:35:39,332 basehttp 15192 19284 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 17:35:39,434 basehttp 15192 21808 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:35:39,540 basehttp 15192 21808 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:35:44,460 basehttp 15192 21808 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:35:44,482 basehttp 15192 19284 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:35:44,915 basehttp 15192 21336 "OPTIONS /api/properties/?featured=true&limit=6 HTTP/1.1" 200 0
INFO 2025-10-18 17:35:44,915 basehttp 15192 11348 "OPTIONS /api/auth/me/ HTTP/1.1" 200 0
INFO 2025-10-18 17:35:44,934 basehttp 15192 21808 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 17:35:45,079 basehttp 15192 19284 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:41:16,499 autoreload 15192 10584 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 17:41:19,297 autoreload 19396 344 Watching for file changes with StatReloader
INFO 2025-10-18 17:41:34,538 autoreload 19396 344 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 17:41:35,969 autoreload 22636 13172 Watching for file changes with StatReloader
INFO 2025-10-18 17:44:16,770 basehttp 22636 21068 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:44:16,777 basehttp 22636 21068 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:44:17,005 basehttp 22636 24088 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 17:44:17,106 basehttp 22636 21068 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 1755
INFO 2025-10-18 17:44:17,181 basehttp 22636 21068 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:44:51,144 basehttp 22636 740 "OPTIONS /api/properties/2/favorite/ HTTP/1.1" 200 0
WARNING 2025-10-18 17:44:51,461 log 22636 2288 Forbidden: /api/properties/2/favorite/
WARNING 2025-10-18 17:44:51,462 basehttp 22636 2288 "POST /api/properties/2/favorite/ HTTP/1.1" 403 58
INFO 2025-10-18 17:47:26,455 autoreload 22636 13172 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 17:47:27,907 autoreload 15620 2404 Watching for file changes with StatReloader
INFO 2025-10-18 17:47:38,532 basehttp 15620 1236 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:47:38,547 basehttp 15620 16712 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:47:38,593 basehttp 15620 16712 "GET /api/auth/me/ HTTP/1.1" 200 32
ERROR 2025-10-18 17:47:38,848 log 15620 1236 Internal Server Error: /api/properties/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `is_favorited` is not valid for model `Property` in `properties.serializers.PropertyListSerializer`.
ERROR 2025-10-18 17:47:38,864 basehttp 15620 1236 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 500 168860
INFO 2025-10-18 17:48:03,064 basehttp 15620 1236 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:48:03,066 basehttp 15620 16712 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:48:03,281 basehttp 15620 1236 "GET /api/auth/me/ HTTP/1.1" 200 32
ERROR 2025-10-18 17:48:03,647 log 15620 16712 Internal Server Error: /api/properties/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `is_favorited` is not valid for model `Property` in `properties.serializers.PropertyListSerializer`.
ERROR 2025-10-18 17:48:03,663 basehttp 15620 16712 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 500 168860
INFO 2025-10-18 17:51:29,636 autoreload 15620 2404 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 17:51:31,107 autoreload 7432 17060 Watching for file changes with StatReloader
INFO 2025-10-18 17:51:44,385 basehttp 7432 22128 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:51:44,394 basehttp 7432 22128 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:51:44,614 basehttp 7432 16512 "GET /api/auth/me/ HTTP/1.1" 200 32
ERROR 2025-10-18 17:51:44,723 log 7432 22128 Internal Server Error: /api/properties/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `is_favorited` is not valid for model `Property` in `properties.serializers.PropertyListSerializer`.
ERROR 2025-10-18 17:51:44,738 basehttp 7432 22128 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 500 168860
INFO 2025-10-18 17:51:48,424 basehttp 7432 22128 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:51:48,426 basehttp 7432 15508 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:51:48,591 basehttp 7432 22128 "GET /api/auth/me/ HTTP/1.1" 200 32
ERROR 2025-10-18 17:51:48,920 log 7432 15508 Internal Server Error: /api/properties/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `is_favorited` is not valid for model `Property` in `properties.serializers.PropertyListSerializer`.
ERROR 2025-10-18 17:51:48,956 basehttp 7432 15508 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 500 168860
INFO 2025-10-18 17:52:18,194 autoreload 7432 17060 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 17:52:19,771 autoreload 14208 24564 Watching for file changes with StatReloader
INFO 2025-10-18 17:52:26,404 basehttp 14208 13028 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:52:26,404 basehttp 14208 23480 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:52:26,442 basehttp 14208 13028 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 17:52:26,619 basehttp 14208 23480 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4125
INFO 2025-10-18 17:52:26,675 basehttp 14208 23480 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:52:58,828 basehttp 14208 2908 "OPTIONS /api/properties/5/favorite/ HTTP/1.1" 200 0
WARNING 2025-10-18 17:52:59,152 log 14208 10900 Forbidden: /api/properties/5/favorite/
WARNING 2025-10-18 17:52:59,153 basehttp 14208 10900 "POST /api/properties/5/favorite/ HTTP/1.1" 403 58
INFO 2025-10-18 17:54:27,614 autoreload 14208 24564 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 17:54:29,463 autoreload 22544 22676 Watching for file changes with StatReloader
INFO 2025-10-18 17:54:36,567 autoreload 22544 22676 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 17:54:38,075 autoreload 20436 19664 Watching for file changes with StatReloader
INFO 2025-10-18 17:54:44,032 autoreload 20436 19664 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 17:54:45,149 autoreload 25156 2136 Watching for file changes with StatReloader
INFO 2025-10-18 17:56:06,193 basehttp 25156 22300 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:56:06,358 basehttp 25156 22300 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 17:56:06,384 basehttp 25156 22300 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 17:56:23,393 basehttp 25156 4952 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 17:56:23,553 basehttp 25156 4952 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4188
INFO 2025-10-18 18:13:45,786 basehttp 25156 12264 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:13:45,798 basehttp 25156 12264 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:13:46,233 basehttp 25156 21704 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 18:13:46,669 basehttp 25156 12264 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4188
INFO 2025-10-18 18:13:47,101 basehttp 25156 12264 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:13:47,388 basehttp 25156 12264 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4188
INFO 2025-10-18 18:15:09,001 basehttp 25156 9504 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:15:09,012 basehttp 25156 9504 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:15:09,377 basehttp 25156 2076 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 18:15:09,561 basehttp 25156 9504 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4188
INFO 2025-10-18 18:15:16,946 basehttp 25156 20516 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:15:17,004 basehttp 25156 13776 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:15:17,038 basehttp 25156 13776 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 18:15:17,221 basehttp 25156 20516 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4188
INFO 2025-10-18 18:15:17,302 basehttp 25156 20516 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 18:18:20,201 basehttp 25156 2780 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:18:20,508 basehttp 25156 2780 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 18:18:20,557 basehttp 25156 2780 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 18:18:28,526 basehttp 25156 8952 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:18:28,843 basehttp 25156 23172 "OPTIONS /api/properties/? HTTP/1.1" 200 0
INFO 2025-10-18 18:18:29,100 basehttp 25156 8952 "GET /api/properties/? HTTP/1.1" 200 6206
INFO 2025-10-18 18:18:35,554 basehttp 25156 16168 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:18:35,741 basehttp 25156 16168 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4188
INFO 2025-10-18 18:19:20,626 basehttp 25156 8560 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:19:20,855 basehttp 25156 8560 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 18:19:23,958 basehttp 25156 22564 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:19:24,311 basehttp 25156 22564 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4188
INFO 2025-10-18 18:20:17,651 basehttp 25156 14196 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:20:17,838 basehttp 25156 14196 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 18:20:19,396 basehttp 25156 14196 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:20:19,666 basehttp 25156 14196 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4188
INFO 2025-10-18 18:23:16,844 basehttp 25156 23336 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:23:17,181 basehttp 25156 22016 "OPTIONS /api/auth/login/ HTTP/1.1" 200 0
WARNING 2025-10-18 18:23:18,779 log 25156 19388 Unauthorized: /api/auth/login/
WARNING 2025-10-18 18:23:18,780 basehttp 25156 19388 "POST /api/auth/login/ HTTP/1.1" 401 52
INFO 2025-10-18 18:23:32,408 basehttp 25156 11696 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:23:32,416 basehttp 25156 11696 "GET /api/auth/me/ HTTP/1.1" 200 32
INFO 2025-10-18 18:23:41,064 basehttp 25156 3956 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:23:42,415 basehttp 25156 3956 "POST /api/auth/login/ HTTP/1.1" 200 918
INFO 2025-10-18 18:23:42,490 basehttp 25156 3956 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:23:42,500 basehttp 25156 3956 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:23:42,841 basehttp 25156 23060 "OPTIONS /api/auth/dashboard/overview/ HTTP/1.1" 200 0
INFO 2025-10-18 18:23:42,848 basehttp 25156 23480 "OPTIONS /api/properties/my_properties/ HTTP/1.1" 200 0
INFO 2025-10-18 18:23:43,071 basehttp 25156 10244 "GET /api/properties/my_properties/ HTTP/1.1" 200 4021
ERROR 2025-10-18 18:23:43,161 log 25156 3956 Internal Server Error: /api/auth/dashboard/overview/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\users\views.py", line 183, in dashboard_overview
    my_listings = Property.objects.filter(owner=user)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1806, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'owner' into field. Choices are: address, agent, agent_id, amenities, bathrooms, bedrooms, city, contact_info, created_at, deposit_percentage, description, discount_offers, distance_to_main_road, documents, electricity_availability, favorited_by, featured, has_beacons, has_borehole, has_central_air, has_drainage, has_fireplace, has_garage, has_garden, has_piped_water, has_pool, has_sewer_system, has_subdivision_approval, id, images, inquiries, inquiry_count, internet_availability, is_fenced, is_gated_community, is_negotiable, land_type, landmarks, latitude, longitude, lot_size, media, num_plots_available, payment_plan_details, plot_dimensions, price, price_per_unit, price_unit, property_type, published_at, road_access_type, seller, seller_id, short_description, size_acres, soil_type, square_feet, state, status, title, title_deed_status, topography, total_plots, updated_at, useractivity, views_count, water_supply_types, year_built, zip_code, zoning
ERROR 2025-10-18 18:23:43,187 basehttp 25156 3956 "GET /api/auth/dashboard/overview/ HTTP/1.1" 500 164392
INFO 2025-10-18 18:23:50,784 basehttp 25156 22196 "GET /api/auth/csrf/ HTTP/1.1" 200 81
ERROR 2025-10-18 18:23:51,043 log 25156 22196 Internal Server Error: /api/properties/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py", line 123, in get_is_favorited
    return obj.favorites.filter(user=request.user).exists()
           ^^^^^^^^^^^^^
AttributeError: 'Property' object has no attribute 'favorites'. Did you mean: 'favorited_by'?
ERROR 2025-10-18 18:23:51,062 basehttp 25156 22196 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 500 172073
INFO 2025-10-18 18:30:33,412 basehttp 25156 9088 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:30:33,426 basehttp 25156 9088 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:30:33,849 basehttp 25156 12576 "GET /api/properties/my_properties/ HTTP/1.1" 200 4021
ERROR 2025-10-18 18:30:33,905 log 25156 9088 Internal Server Error: /api/auth/dashboard/overview/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\users\views.py", line 183, in dashboard_overview
    my_listings = Property.objects.filter(owner=user)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\db\models\sql\query.py", line 1806, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'owner' into field. Choices are: address, agent, agent_id, amenities, bathrooms, bedrooms, city, contact_info, created_at, deposit_percentage, description, discount_offers, distance_to_main_road, documents, electricity_availability, favorited_by, featured, has_beacons, has_borehole, has_central_air, has_drainage, has_fireplace, has_garage, has_garden, has_piped_water, has_pool, has_sewer_system, has_subdivision_approval, id, images, inquiries, inquiry_count, internet_availability, is_fenced, is_gated_community, is_negotiable, land_type, landmarks, latitude, longitude, lot_size, media, num_plots_available, payment_plan_details, plot_dimensions, price, price_per_unit, price_unit, property_type, published_at, road_access_type, seller, seller_id, short_description, size_acres, soil_type, square_feet, state, status, title, title_deed_status, topography, total_plots, updated_at, useractivity, views_count, water_supply_types, year_built, zip_code, zoning
ERROR 2025-10-18 18:30:33,936 basehttp 25156 9088 "GET /api/auth/dashboard/overview/ HTTP/1.1" 500 164392
INFO 2025-10-18 18:36:09,824 basehttp 25156 13596 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:36:10,151 basehttp 25156 2252 "OPTIONS /api/properties/ HTTP/1.1" 200 0
WARNING 2025-10-18 18:36:10,326 log 25156 13596 Forbidden: /api/properties/
WARNING 2025-10-18 18:36:10,327 basehttp 25156 13596 "POST /api/properties/ HTTP/1.1" 403 108
INFO 2025-10-18 18:36:10,337 basehttp 25156 13596 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:36:10,347 basehttp 25156 2252 "OPTIONS /api/properties/create/ HTTP/1.1" 200 0
WARNING 2025-10-18 18:36:10,471 log 25156 13596 Forbidden: /api/properties/create/
WARNING 2025-10-18 18:36:10,472 basehttp 25156 13596 "POST /api/properties/create/ HTTP/1.1" 403 108
INFO 2025-10-18 18:36:10,483 basehttp 25156 13596 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:36:10,491 basehttp 25156 2252 "OPTIONS /api/create/ HTTP/1.1" 200 0
WARNING 2025-10-18 18:36:10,603 log 25156 13596 Forbidden: /api/create/
WARNING 2025-10-18 18:36:10,604 basehttp 25156 13596 "POST /api/create/ HTTP/1.1" 403 108
INFO 2025-10-18 18:52:59,414 basehttp 25156 10632 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:52:59,961 basehttp 25156 10632 "GET /api/auth/me/ HTTP/1.1" 200 887
INFO 2025-10-18 18:54:49,756 basehttp 25156 8740 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 18:54:50,129 basehttp 25156 8740 "GET /api/auth/me/ HTTP/1.1" 200 887
INFO 2025-10-18 18:59:18,973 basehttp 25156 19792 "GET /api/auth/csrf/ HTTP/1.1" 200 81
WARNING 2025-10-18 18:59:19,142 log 25156 19792 Forbidden: /api/properties/
WARNING 2025-10-18 18:59:19,144 basehttp 25156 19792 "POST /api/properties/ HTTP/1.1" 403 108
INFO 2025-10-18 18:59:19,157 basehttp 25156 19792 "GET /api/auth/csrf/ HTTP/1.1" 200 81
WARNING 2025-10-18 18:59:19,283 log 25156 19792 Forbidden: /api/properties/create/
WARNING 2025-10-18 18:59:19,284 basehttp 25156 19792 "POST /api/properties/create/ HTTP/1.1" 403 108
INFO 2025-10-18 18:59:19,293 basehttp 25156 19792 "GET /api/auth/csrf/ HTTP/1.1" 200 81
WARNING 2025-10-18 18:59:19,389 log 25156 19792 Forbidden: /api/create/
WARNING 2025-10-18 18:59:19,390 basehttp 25156 19792 "POST /api/create/ HTTP/1.1" 403 108
INFO 2025-10-18 19:06:22,086 basehttp 25156 23152 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:06:22,359 basehttp 25156 23152 "GET /api/auth/me/ HTTP/1.1" 200 887
INFO 2025-10-18 19:06:29,641 basehttp 25156 23152 "GET /api/auth/csrf/ HTTP/1.1" 200 81
ERROR 2025-10-18 19:06:30,349 log 25156 23152 Internal Server Error: /api/properties/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py", line 123, in get_is_favorited
    return obj.favorites.filter(user=request.user).exists()
           ^^^^^^^^^^^^^
AttributeError: 'Property' object has no attribute 'favorites'. Did you mean: 'favorited_by'?
ERROR 2025-10-18 19:06:30,378 basehttp 25156 23152 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 500 172073
INFO 2025-10-18 19:06:39,068 basehttp 25156 23152 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:06:39,083 basehttp 25156 23152 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:06:39,857 basehttp 25156 10464 "GET /api/auth/me/ HTTP/1.1" 200 887
ERROR 2025-10-18 19:06:39,973 log 25156 23152 Internal Server Error: /api/properties/
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py", line 123, in get_is_favorited
    return obj.favorites.filter(user=request.user).exists()
           ^^^^^^^^^^^^^
AttributeError: 'Property' object has no attribute 'favorites'. Did you mean: 'favorited_by'?
ERROR 2025-10-18 19:06:40,006 basehttp 25156 23152 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 500 172073
INFO 2025-10-18 19:09:23,780 autoreload 25156 2136 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 19:09:25,942 autoreload 16504 17888 Watching for file changes with StatReloader
INFO 2025-10-18 19:10:06,152 autoreload 16504 17888 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\properties\serializers.py changed, reloading.
INFO 2025-10-18 19:10:07,635 autoreload 22120 15236 Watching for file changes with StatReloader
INFO 2025-10-18 19:10:18,753 basehttp 22120 3600 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:10:18,768 basehttp 22120 3600 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:10:19,092 basehttp 22120 22696 "OPTIONS /api/properties/?featured=true&limit=6 HTTP/1.1" 200 0
INFO 2025-10-18 19:10:19,098 basehttp 22120 22696 "OPTIONS /api/auth/me/ HTTP/1.1" 200 0
INFO 2025-10-18 19:10:19,383 basehttp 22120 3600 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4125
INFO 2025-10-18 19:10:19,385 basehttp 22120 16268 "GET /api/auth/me/ HTTP/1.1" 200 887
INFO 2025-10-18 19:10:19,481 basehttp 22120 16268 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 19:22:38,757 basehttp 22120 19072 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:22:39,082 basehttp 22120 7084 "OPTIONS /api/properties/?property_type=rental&status=published HTTP/1.1" 200 0
INFO 2025-10-18 19:22:39,345 basehttp 22120 19072 "GET /api/properties/?property_type=rental&status=published HTTP/1.1" 200 1091
INFO 2025-10-18 19:23:43,282 basehttp 22120 9404 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:23:43,500 basehttp 22120 9404 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4125
INFO 2025-10-18 19:23:43,549 basehttp 22120 9404 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 19:24:15,054 basehttp 22120 23856 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:24:15,374 basehttp 22120 18052 "OPTIONS /api/properties/5/ HTTP/1.1" 200 0
INFO 2025-10-18 19:24:15,548 basehttp 22120 23856 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 19:24:15,569 basehttp 22120 23856 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 19:29:45,843 basehttp 22120 16808 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:29:46,091 basehttp 22120 16808 "GET /api/properties/? HTTP/1.1" 200 6101
INFO 2025-10-18 19:30:56,700 basehttp 22120 16808 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:30:56,886 basehttp 22120 16808 "GET /api/properties/5/ HTTP/1.1" 200 4353
ERROR 2025-10-18 19:51:57,107 log 22120 9956 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 19:51:57,136 basehttp 22120 9956 "GET /favicon.ico HTTP/1.1" 500 92473
INFO 2025-10-18 19:52:00,265 basehttp 22120 9956 "GET /admin/properties/property/5/change/ HTTP/1.1" 200 116494
ERROR 2025-10-18 19:52:01,044 log 22120 9956 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 19:52:01,056 basehttp 22120 9956 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 19:52:23,881 basehttp 22120 9956 "GET /admin/properties/propertyimage/add/ HTTP/1.1" 200 22459
INFO 2025-10-18 19:52:24,021 basehttp 22120 9956 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 19:52:24,267 log 22120 9956 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 19:52:24,275 basehttp 22120 9956 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 19:52:29,330 basehttp 22120 9956 "GET /admin/properties/propertymedia/add/ HTTP/1.1" 200 24817
INFO 2025-10-18 19:52:29,607 basehttp 22120 9956 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-18 19:52:29,805 log 22120 9956 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2025-10-18 19:52:29,813 basehttp 22120 9956 "GET /favicon.ico HTTP/1.1" 500 92508
INFO 2025-10-18 19:54:06,484 basehttp 22120 2252 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:54:07,126 basehttp 22120 2252 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 19:54:07,180 basehttp 22120 2252 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:54:07,499 basehttp 22120 19460 "OPTIONS /api/properties/5/increment-views/ HTTP/1.1" 200 0
INFO 2025-10-18 19:54:07,680 basehttp 22120 2252 "GET /api/properties/5/increment-views/ HTTP/1.1" 200 17
INFO 2025-10-18 19:54:35,263 basehttp 22120 16552 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:54:35,487 basehttp 22120 16552 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 19:54:35,497 basehttp 22120 16552 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:54:35,654 basehttp 22120 16552 "GET /api/properties/5/increment-views/ HTTP/1.1" 200 17
INFO 2025-10-18 19:55:02,993 basehttp 22120 4916 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:55:03,283 basehttp 22120 4916 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4125
INFO 2025-10-18 19:55:03,335 basehttp 22120 4916 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 19:55:21,601 basehttp 22120 16140 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:55:21,842 basehttp 22120 16140 "GET /api/properties/5/ HTTP/1.1" 200 4353
INFO 2025-10-18 19:55:21,871 basehttp 22120 16140 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:55:22,006 basehttp 22120 16140 "GET /api/properties/5/increment-views/ HTTP/1.1" 200 17
INFO 2025-10-18 19:55:22,032 basehttp 22120 16140 "GET /media/property_images/2025/10/18/download_4.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 19:58:39,386 basehttp 22120 21808 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:58:39,640 basehttp 22120 21808 "GET /api/properties/? HTTP/1.1" 200 6101
INFO 2025-10-18 19:58:41,326 basehttp 22120 21808 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 19:58:41,598 basehttp 22120 21808 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4125
INFO 2025-10-18 20:13:32,076 basehttp 22120 2740 "GET /api/auth/csrf/ HTTP/1.1" 200 81
INFO 2025-10-18 20:13:32,489 basehttp 22120 2740 "GET /api/properties/?featured=true&limit=6 HTTP/1.1" 200 4125
INFO 2025-10-18 20:13:32,556 basehttp 22120 2740 "GET /media/property_images/2025/10/18/images_5.jpeg HTTP/1.1" 304 0
INFO 2025-10-18 20:38:38,932 autoreload 22120 15236 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\pristineprimer\settings.py changed, reloading.
INFO 2025-10-18 20:38:42,427 autoreload 15156 21852 Watching for file changes with StatReloader
INFO 2025-10-18 20:58:24,059 autoreload 15156 21852 C:\Users\User1\Documents\PayedProjects\Pristineprimier_real_estate_Website\server\pristineprimer\settings.py changed, reloading.
